export interface Certificate {
  title: string;
  icon: string;
  platform: string;
  tutor: string;
  completedDate: string;
  visibility: boolean;
}

export const CERTIFICATES: Certificate[] = [
  {
    title: 'Baue Webseiten mit HTML5 & CSS3.',
    icon: 'HTML',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: 'Fortgeschrittenes CSS: Animationen, Flexbox, SASS, SVG, 3D.',
    icon: 'CSS',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: 'Git Komplettkurs: Vom Anfänger zum Profi (inkl. GitHub).',
    icon: 'GIT',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: 'Sass Grundkurs.',
    icon: 'SCSS',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: 'Die komplette JavaScript Masterclass.',
    icon: 'javaScript',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: 'Clean Code.',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: 'Chrome DevTools verstehen und verwenden.',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: 'Angular – The Complete Guide.',
    icon: 'angular',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 1',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 2',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 3',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 4',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 5',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 6',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 7',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 8',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 9',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 10',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 11',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 12',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 13',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 14',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 15',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 16',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 17',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
  {
    title: '#Dummy Kurs 18',
    icon: 'dot',
    platform: 'Udemy',
    tutor: '',
    completedDate: '',
    visibility: true,
  },
];
