export interface Certificate {
  title: string;
  icon: string;
  platform: string;
  tutor: string;
  date: string;
  image: string;
  visibility: boolean;
}

export const CERTIFICATES: Certificate[] = [
  {
    title: 'Developer Akademie',
    icon: 'dot',
    platform: 'Developer Akademie',
    tutor: 'Developer Akademie',
    date: '12.2024',
    image: './certificates/developer_akademie.webp',
    visibility: true,
  },
  {
    title: 'Baue Webseiten mit HTML5 & CSS3.',
    icon: 'HTML',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '01.2024',
    image:
      './certificates/udemy/baue_webseiten_mit_html5_css3_vom_anfaenger_zum_profi!.webp',
    visibility: true,
  },
  {
    title: 'Fortgeschrittenes CSS: Animationen, Flexbox, SASS, SVG, 3D.',
    icon: 'CSS',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '04.2024',
    image:
      './certificates/udemy/fortgeschrittenes_css_animationen_flexbox_svg_3d_sass.webp',
    visibility: true,
  },
  {
    title: 'Docker komplett Vom Anfänger zum Profi (inkl. Kubernetes)',
    icon: 'docker',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '07.2024',
    image:
      './certificates/udemy/docker_komplett_vom_anfaenger_zum_profi_inkl_kubernetes.webp',
    visibility: true,
  },
  {
    title: 'Git Komplettkurs: Vom Anfänger zum Profi (inkl. GitHub).',
    icon: 'GIT',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '08.2024',
    image:
      './certificates/udemy/git_komplettkurs_vom_anfaenger_zum_profi_inkl_github.webp',
    visibility: true,
  },
  {
    title: 'Schnelleinstieg in TypeScript.',
    icon: 'typeScript',
    platform: 'Udemy',
    tutor: 'Jan Schaffranek',
    date: '10.2024',
    image: './certificates/udemy/schnelleinstieg_in_typescript.webp',
    visibility: true,
  },

  {
    title: 'Sass Grundkurs.',
    icon: 'SCSS',
    platform: 'Linkedin',
    tutor: 'Florence Maurice',
    date: '10.2024',
    image: './certificates/linkedin/abschlusszertifikat_sass_grundkurs.webp',
    visibility: true,
  },
  {
    title: 'Affinity Designer Grundkurs.',
    icon: 'dot',
    platform: 'Linkedin',
    tutor: 'Michael Rüttger',
    date: '12.2024',
    image:
      './certificates/linkedin/abschlusszertifikat_affinity_designer_grundkurs.webp',
    visibility: true,
  },
  {
    title: 'Figma Grundkurs.',
    icon: 'figma',
    platform: 'Linkedin',
    tutor: 'Maureen Herben',
    date: '12.2024',
    image: './certificates/linkedin/abschlusszertifikat_figma_grundkurs.webp',
    visibility: true,
  },

  {
    title: 'Die komplette JavaScript Masterclass.',
    icon: 'javaScript',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '12.2024',
    image:
      './certificates/udemy/die_komplette_javascript_masterclass_vom_anfaenger_zum_profi.webp',
    visibility: true,
  },
  {
    title: 'Clean Code.',
    icon: 'dot',
    platform: 'Udemy',
    tutor: 'Maximilian Schwarzmüller',
    date: '12.2024',
    image: './certificates/udemy/clean_code.webp',
    visibility: true,
  },
  // {
  //   title: 'Chrome DevTools verstehen und verwenden.',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Stephan Haewß',
  //   date: '',
  //   image: './certificates/udemy/',
  //   visibility: false,
  // },
  // {
  //   title: 'Angular – The Complete Guide.',
  //   icon: 'angular',
  //   platform: 'Udemy',
  //   tutor: 'Maximilian Schwarzmüller',
  //   date: '',
  //   image: './certificates/udemy/',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 1',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 2',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 3',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 4',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 5',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 6',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 7',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 8',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 9',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 10',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 11',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 12',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 13',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 14',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 15',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 16',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 17',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
  // {
  //   title: '#Dummy Kurs 18',
  //   icon: 'dot',
  //   platform: 'Udemy',
  //   tutor: 'Max Mustermann',
  //   date: '12.2024',
  //   image: '',
  //   visibility: false,
  // },
];
