export interface Certificate {
  titleDE: string;
  titleEN: string;
  icon: string;
  platform: string;
  tutor: string;
  date: string;
  image: string;
  visibility: boolean;
}

// {
//   titleDE: '',
//   titleEN: '',
//   icon: '',
//   platform: '',
//   tutor: '',
//   date: '',
//   image: '',
//   visibility: false,
// },
export const CERTIFICATES: Certificate[] = [
  {
    titleDE: 'Angular – The Complete Guide',
    titleEN: 'Angular – The Complete Guide',
    icon: 'angular',
    platform: 'Udemy',
    tutor: 'Maximilian Schwarzmüller',
    date: '',
    image: './certificates/udemy/',
    visibility: false,
  },
  {
    titleDE: 'Chrome DevTools verstehen und verwenden',
    titleEN: 'Understand and use Chrome DevTools',
    icon: 'chrome',
    platform: 'Udemy',
    tutor: 'Stephan Haewß',
    date: '',
    image: './certificates/udemy/',
    visibility: false,
  },
  {
    titleDE: 'Schnelleinstieg in die Python Programmierung für Anfänger',
    titleEN: 'Quick start in Python programming for beginners',
    icon: 'python',
    platform: 'Udemy',
    tutor: 'Jan Schaffranek',
    date: '02.2026',
    image:
      './certificates/udemy/schnelleinstieg_in_die_python_programmierung_fuer_anfaenger.webp',
    visibility: true,
  },
  {
    titleDE: 'Django - Der umfangreiche Einsteigerkurs zur Webentwicklung',
    titleEN: 'Django - The comprehensive beginners course for web development',
    icon: 'django',
    platform: 'Udemy',
    tutor: 'Fabian Heihoff',
    date: '10.2025',
    image:
      './certificates/udemy/django_der_umfangreiche_einsteigerkurs_zur_webentwicklung.webp',
    visibility: true,
  },
  {
    titleDE: 'Electron - Einstieg in die Entwicklung von Desktop Apps',
    titleEN: 'Electron - Introduction to desktop app development',
    icon: 'electron',
    platform: 'Udemy',
    tutor: 'Fabian Heihoff',
    date: '10.2025',
    image:
      './certificates/udemy/electron_einstieg_in_die_entwicklung_von_desktop_apps.webp',
    visibility: true,
  },
  {
    titleDE: 'Next.js - Das React Framework für moderne Webanwendungen',
    titleEN: 'Next.js - The React framework for modern web applications',
    icon: 'next_js',
    platform: 'Udemy',
    tutor: 'Fabian Heihoff',
    date: '09.2025',
    image:
      './certificates/udemy/next_js_das_react_framework_fuer_moderne_webanwendungen.webp',
    visibility: true,
  },
  {
    titleDE: 'Der komplette WordPress - Kurs für Einsteiger',
    titleEN: 'The complete WordPress course for beginners',
    icon: 'wordpress',
    platform: 'Udemy',
    tutor: 'Meta Brains',
    date: '09.2025',
    image:
      './certificates/udemy/der_komplette_wordpress_kurs_fuer_einsteiger.webp',
    visibility: false,
  },
  {
    titleDE: 'Symfony - Der umfassende Grundkurs für Einsteiger',
    titleEN: 'Symfony - The comprehensive basic course for beginners',
    icon: 'symfony',
    platform: 'Udemy',
    tutor: 'Fabian Heihoff',
    date: '07.2025',
    image:
      './certificates/udemy/symfony_der_umfassende_grundkurs_fuer_einsteiger.webp',
    visibility: true,
  },
  {
    titleDE: 'Die komplette SQL Masterclass',
    titleEN: 'The complete SQL Masterclass',
    icon: 'database',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '07.2025',
    image:
      './certificates/udemy/die_komplette_sql_masterclass_vom_anfaenger_zum_profi.webp',
    visibility: true,
  },
  {
    titleDE: 'Postman von Grund auf – REST API testen',
    titleEN: 'Postman from scratch - Test REST API',
    icon: 'postman',
    platform: 'Udemy',
    tutor: 'Rafał Podraza',
    date: '03.2025',
    image: './certificates/udemy/postman_von_grund_auf_rest_api_testen.webp',
    visibility: true,
  },
  {
    titleDE: 'API Entwicklung mit PHP Laravel - Best Practice RESTFul APIs',
    titleEN: 'API development with PHP Laravel - Best Practice RESTFul APIs',
    icon: 'API',
    platform: 'Udemy',
    tutor: 'Andreas Pabst',
    date: '02.2025',
    image:
      './certificates/udemy/api_entwicklung_mit_php_laravel_best_practice_restful_apis.webp',
    visibility: true,
  },
  {
    titleDE: 'Laravel Kurs für Einsteiger',
    titleEN: 'Laravel course for beginners',
    icon: 'laravel',
    platform: 'Udemy',
    tutor: 'Andreas Pabst',
    date: '02.2025',
    image: './certificates/udemy/laravel_kurs_fuer_einsteiger.webp',
    visibility: true,
  },
  {
    titleDE: 'PHP Der ultimative Komplettkurs für Webentwicklung mit PHP',
    titleEN: 'PHP The ultimate complete course for web development with PHP',
    icon: 'PHP',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '02.2025',
    image:
      './certificates/udemy/php_der_ultimative_komplettkurs_fuer_webentwicklung_mit_php.webp',
    visibility: true,
  },
  {
    titleDE: 'Clean Code',
    titleEN: 'Clean Code',
    icon: 'cleanCode',
    platform: 'Udemy',
    tutor: 'Maximilian Schwarzmüller',
    date: '12.2024',
    image: './certificates/udemy/clean_code.webp',
    visibility: true,
  },
  {
    titleDE: 'Die komplette JavaScript Masterclass',
    titleEN: 'The complete JavaScript Masterclass',
    icon: 'javaScript',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '12.2024',
    image:
      './certificates/udemy/die_komplette_javascript_masterclass_vom_anfaenger_zum_profi.webp',
    visibility: true,
  },
  {
    titleDE: 'Figma Grundkurs',
    titleEN: 'Figma basic course',
    icon: 'figma',
    platform: 'Linkedin',
    tutor: 'Maureen Herben',
    date: '12.2024',
    image: './certificates/linkedin/abschlusszertifikat_figma_grundkurs.webp',
    visibility: true,
  },
  {
    titleDE: 'Affinity Designer Grundkurs',
    titleEN: 'Affinity Designer basic course',
    icon: 'affinityDesigner',
    platform: 'Linkedin',
    tutor: 'Michael Rüttger',
    date: '12.2024',
    image:
      './certificates/linkedin/abschlusszertifikat_affinity_designer_grundkurs.webp',
    visibility: false,
  },
  {
    titleDE: 'Developer Akademie - Praxisorientierter Frontend Kurs',
    titleEN: 'Developer Akademie - Practice-oriented frontend course',
    icon: 'developerAkademie',
    platform: 'Developer Akademie',
    tutor: 'Developer Akademie',
    date: '12.2024',
    image: './certificates/developer_akademie.webp',
    visibility: true,
  },
  {
    titleDE: 'Sass Grundkurs',
    titleEN: 'Sass basic course',
    icon: 'SCSS',
    platform: 'Linkedin',
    tutor: 'Florence Maurice',
    date: '10.2024',
    image: './certificates/linkedin/abschlusszertifikat_sass_grundkurs.webp',
    visibility: true,
  },
  {
    titleDE: 'Schnelleinstieg in TypeScript',
    titleEN: 'Quick start in TypeScript',
    icon: 'typeScript',
    platform: 'Udemy',
    tutor: 'Jan Schaffranek',
    date: '10.2024',
    image: './certificates/udemy/schnelleinstieg_in_typescript.webp',
    visibility: true,
  },
  {
    titleDE: 'Git Komplettkurs - Vom Anfänger zum Profi',
    titleEN: 'Git Complete Course - From Beginner to Professional',
    icon: 'GIT',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '08.2024',
    image:
      './certificates/udemy/git_komplettkurs_vom_anfaenger_zum_profi_inkl_github.webp',
    visibility: true,
  },
  {
    titleDE: 'Docker komplett Vom Anfänger zum Profi',
    titleEN: 'Docker complete From beginner to professional',
    icon: 'docker',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '07.2024',
    image:
      './certificates/udemy/docker_komplett_vom_anfaenger_zum_profi_inkl_kubernetes.webp',
    visibility: true,
  },
  {
    titleDE: 'Fortgeschrittenes CSS - Animationen, Flexbox, SASS, SVG, 3D',
    titleEN: 'Advanced CSS - Animations, Flexbox, SASS, SVG, 3D',
    icon: 'CSS',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '04.2024',
    image:
      './certificates/udemy/fortgeschrittenes_css_animationen_flexbox_svg_3d_sass.webp',
    visibility: true,
  },
  {
    titleDE: 'Baue Webseiten mit HTML5 & CSS3',
    titleEN: 'Build Websites with HTML5 & CSS3',
    icon: 'HTML',
    platform: 'Udemy',
    tutor: 'Jannis Seemann',
    date: '01.2024',
    image:
      './certificates/udemy/baue_webseiten_mit_html5_css3_vom_anfaenger_zum_profi!.webp',
    visibility: true,
  },
];
